### ISSUE TITLE
Can not start app after installing the package on RN 0.73

### ISSUE THREAD

**Issue by yossularko** [trustee-wallet/vision-camera-trustee-face-detector-v3#1]
`D:\ReactNative\~NewRN\RNVisionCameraV3\node_modules\vision-camera-trustee-face-detector-v3\android\src\main\java\com\visioncamerafacedetector\VisionCameraFaceDetectorPlugin.java:167: error: constructor FrameProcessorPlugin in class FrameProcessorPlugin cannot be applied to given types;`
`    super(options);`
`    ^`
`  required: no arguments`
`  found:    Map<String,Object>`
`  reason: actual and formal argument lists differ in length`
`D:\ReactNative\~NewRN\RNVisionCameraV3\node_modules\vision-camera-trustee-face-detector-v3\android\src\main\java\com\visioncamerafacedetector\VisionCameraFaceDetectorPluginPackage.java:18: error: incompatible types: incompatible parameter types in lambda expression`
`    FrameProcessorPluginRegistry.addFrameProcessorPlugin("detectFaces", options -> new VisionCameraFaceDetectorPlugin(options));`
`                                                                        ^`
`D:\ReactNative\~NewRN\RNVisionCameraV3\node_modules\vision-camera-trustee-face-detector-v3\android\src\main\java\com\visioncamerafacedetector\VisionCameraFaceDetectorPluginPackage.java:18: error: incompatible types: VisionCameraProxy cannot be converted to Map<String,Object>`
`    FrameProcessorPluginRegistry.addFrameProcessorPlugin("detectFaces", options -> new VisionCameraFaceDetectorPlugin(options));`
`                                                                                                                      ^`
`Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output 3 errors`

`FAILURE: Build failed with an exception.`

`* What went wrong:
Execution failed for task ':vision-camera-trustee-face-detector-v3:compileDebugJavaWithJavac'.`
`> Compilation failed; see the compiler error output for details.`

here is my packages:
"react": "18.2.0",
    "react-native": "0.73.2",
    "react-native-vector-icons": "^10.0.3",
    "react-native-vision-camera": "^3.8.1",
    "react-native-worklets-core": "^0.2.4",
    "vision-camera-trustee-face-detector-v3": "^1.4.0"

**Comment by luicfrr** [comment]
+1

**Comment by ShchipskiiYura** [comment]
Do you use this code?
```
const scannedFaces = scanFaces(frame, {});
```

Can you try use this please?
```
const scannedFaces = scanFaces(frame, { performanceMode: 'accurate', classificationMode: 'all', contourMode: 'all' });
```

**Comment by luicfrr** [comment]
> Do you use this code?
> 
> ```
> const scannedFaces = scanFaces(frame, {});
> ```
> 
> Can you try use this please?
> 
> ```
> const scannedFaces = scanFaces(frame, { performanceMode: 'accurate', classificationMode: 'all', contourMode: 'all' });
> ```

doesn't work
I can't even compile the project to test it on my device because of the error

**Comment by ShchipskiiYura** [comment]
> > Do you use this code?
> > ```
> > const scannedFaces = scanFaces(frame, {});
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Can you try use this please?
> > ```
> > const scannedFaces = scanFaces(frame, { performanceMode: 'accurate', classificationMode: 'all', contourMode: 'all' });
> > ```
> 
> doesn't work I can't even compile the project to test it on my device because of the error

Could you get more information? java version, node version, etc.

I use RN 0.73.2 & all works

**Comment by luicfrr** [comment]
@ShchipskiiYura
```
~ java --version
openjdk 17.0.7 2023-04-18
OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
OpenJDK 64-Bit Server VM (build 17.0.7+0-17.0.7b1000.6-10550314, mixed mode)

~ node -v
v20.11.0

~ android studio
Android Studio Hedgehog | 2023.1.1 Patch 1
Build #AI-231.9392.1.2311.11255304, built on December 26, 2023
Runtime version: 17.0.7+0-17.0.7b1000.6-10550314 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.2.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 4
Metal Rendering is ON
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false
```

I'm using `3.8.2` version of `react-native-vision-camera`.
Also using react-native new arch.

Error while trying to compile app:
```
MY_MACHINE_DIR/mobile/node_modules/vision-camera-trustee-face-detector-v3/android/src/main/java/com/visioncamerafacedetector/VisionCameraFaceDetectorPlugin.java:198: error: constructor FrameProcessorPlugin in class FrameProcessorPlugin cannot be applied to given types;
    super(options);
    ^
  required: no arguments
  found:    Map<String,Object>
  reason: actual and formal argument lists differ in length
MY_MACHINE_DIR/mobile/node_modules/vision-camera-trustee-face-detector-v3/android/src/main/java/com/visioncamerafacedetector/VisionCameraFaceDetectorPluginPackage.java:18: error: incompatible types: incompatible parameter types in lambda expression
    FrameProcessorPluginRegistry.addFrameProcessorPlugin("detectFaces", options -> new VisionCameraFaceDetectorPlugin(options));
                                                                        ^
MY_MACHINE_DIR/mobile/node_modules/vision-camera-trustee-face-detector-v3/android/src/main/java/com/visioncamerafacedetector/VisionCameraFaceDetectorPluginPackage.java:18: error: incompatible types: VisionCameraProxy cannot be converted to Map<String,Object>
    FrameProcessorPluginRegistry.addFrameProcessorPlugin("detectFaces", options -> new VisionCameraFaceDetectorPlugin(options));
                                                                                                                      ^
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
3 errors
```

**Comment by ShchipskiiYura** [comment]
I don't support new arch of RN

**Comment by luicfrr** [comment]
@ShchipskiiYura I've just tested disabling new arch, deleting `node_modules` and `android` folder and recreating a new freash and clean build. 
Same error happens. 

I think the issue should be reopened as the error is not fixed.

**Comment by ShchipskiiYura** [comment]
Do you enable vision-camera frameProcessor? 
I use "react-native-vision-camera": "^3.7.1", and all works

Maybe is a reason. Could your try please downgrade version lib? thanks

**Comment by ShchipskiiYura** [comment]
maybe this release is causing your problem

https://github.com/mrousavy/react-native-vision-camera/releases/tag/v3.8.0


version of our lib, don't still support this change, I do this ASAP
